server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      mvc:
        routes:
          - id: product-service-create
            uri: lb://product-service
            predicates:
              - Path=/api/products
              - Method=POST

          - id: product-service-update
            uri: lb://product-service
            predicates:
              - Path=/api/products/{id}
              - Method=PUT

          - id: product-service-delete
            uri: lb://product-service
            predicates:
              - Path=/api/products/{id}
              - Method=DELETE

          - id: product-service-search
            uri: lb://product-service
            predicates:
              - Path=/api/products/search
              - Method=GET

          - id: product-service-get-all
            uri: lb://product-service
            predicates:
              - Path=/api/products
              - Method=GET

          - id: product-service-get-by-id
            uri: lb://product-service
            predicates:
              - Path=/api/products/{id}
              - Method=GET

          - id: notification-service
            uri: lb://notification-service
            predicates:
              - Path=/api/notifications/**

          - id: monitoring-service
            uri: lb://monitoring-service
            predicates:
              - Path=/api/monitoring/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: health,info